### ISSUE TITLE
Primary processing revitalized

### ISSUE THREAD

**Issue by wasade** [biocore/American-Gut#161]
- [x] setup `runipys` similar to [IAB](https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/blob/master/runipynbs.py)
- [x] tie into `.travis.yml`, and set `export AG_TESTING=True`
- [x] get sequence and metadata (#162)
- [x] resolve filtering notebook (#163)
- [x] resolve OTU picking notebook (#164)
- [x] prepare for meta analyses (#165) 
- [x] resolve alpha diversity analysis notebook (#166)
- [x] resolve beta diversity analysis notebook (#167)
- [x] resolve taxonomy summaries notebook (#168)
- [x] resolve categories collapse (#169)
- [x] resolve generating of participant results notebook (#170)
- [ ] resolve project wide summary

**Comment by jwdebelius** [comment]
Project wide summary is redundant with #61
