### ISSUE TITLE
Analysis Summary Pipeline

### ISSUE THREAD

**Issue by jwdebelius** [biocore/American-Gut#186]
I'd like to create something similar to the primary processing block, #161, for analysis, with the idea that the backend could be transferred over to Bokeh or similar later.

I think the easiest way to accomplish this might be a build a data dictionary backend, that would let people operate on the metadata, and then a holding object for the classes able to interact with that object. Test could go on top.

This way, we can have light weight, individual notebooks for each analysis step, and hopefully just switch  out plotting code at some point.

I see the steps as:
* Data Dictionary Objects
     * [ ] Parent Question Object (#188)
     * [ ] Categorical Question Objects (Categorical, Clinical, Frequency); (#192)
     * [ ] Boolean Question Objects (Bool, Multiple response); (#193)
     * [ ] Continous Questions (#194)
* [ ] Data handling Object (#195)
* [ ] Data Dictionary for Ag Questions
* [ ] Univariate Alpha diversity notebook with effect size
* [ ] Alpha diversity notebook for Scott Kelley's analysis
* [ ] Univariate Beta diversity notebook with effect size
* [ ] Univariate OTU notebook (different abundance and differential frequency)
* [ ] Univariate PICRUSt Notebook (have discussed this with @mortonjt)
* [ ] Multivariate alpha diversity
* [ ] Multivariate beta diversity

This may be redundant with other repositories, although I think the first step is unique to American Gut.
